[functions]
  external_node_modules = ["express", "config"]
  node_bundler = "esbuild"
  included_files = ["src/storage/*", "config/*"]
[[redirects]]
  force = true
  from = "/API/*"
  status = 200
  to = "/.netlify/functions/api/:splat"